In [1]:
l = [1,2,3,4]

In [2]:
type(l)

list

In [10]:
import numpy as np

In [11]:
a = numpy.array(l)

In [6]:
a

array([1, 2, 3, 4])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype

dtype('int32')

In [23]:
name = [ ['vimal' ,1111 ], ['pop',2222] , ['krish',3333] ]

In [24]:
a1 = np.array(name)

In [25]:
a1

array([['vimal', '1111'],
       ['pop', '2222'],
       ['krish', '3333']], dtype='<U5')

In [26]:
type(a1)

numpy.ndarray

In [27]:
a1.dtype

dtype('<U5')

In [28]:
a1.shape

(3, 2)

In [29]:
x = [1,2,3,4,5,6,7,8,9]

In [30]:
a1 = np.array(x)

In [31]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1.shape

(9,)

In [34]:
a2 = a1.reshape(3,3)

In [35]:
a2.shape

(3, 3)

In [36]:
np.array([0,0,0,0,0,0,0])

array([0, 0, 0, 0, 0, 0, 0])

In [40]:
np.zeros( (5,5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
y = [1,2,3,4]

In [42]:
a3 = np.array(y)

In [44]:
a3 + 10

array([11, 12, 13, 14])

In [47]:
a3 * 3

array([ 3,  6,  9, 12])

In [52]:
np.zeros( (5,5) ) + 6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])