In [1]:
import cv2

In [2]:
cap = cv2.VideoCapture(1)

In [3]:
status , photo = cap.read()

In [4]:
status

True

In [5]:
photo.shape

(480, 640, 3)

In [68]:
cv2.imshow('vimal', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
cap.release()

In [17]:
crop = photo[100:400, 250:550]

In [41]:
crop.shape

(300, 300, 3)

In [45]:
crop[10:20] = [0,255,0]

In [66]:
cv2.imshow('vimal', crop)
cv2.waitKey()
cv2.destroyAllWindows()

In [20]:
crop_resize = cv2.resize(crop, (100,100) )

In [21]:
crop_resize.shape

(100, 100, 3)

In [22]:
cv2.imshow('vimal', crop_resize)
cv2.waitKey()
cv2.destroyAllWindows()

In [23]:
photo.shape

(480, 640, 3)

In [24]:
crop_resize.shape

(100, 100, 3)

In [25]:
import numpy as np

In [26]:
a1 = np.array([1,2,3,4,5,6])

In [27]:
a1

array([1, 2, 3, 4, 5, 6])

In [28]:
a2 = np.array([1,2])

In [29]:
a2

array([1, 2])

In [34]:
a1[2:4] = a2

In [35]:
a2

array([1, 2])

In [36]:
a1

array([1, 2, 1, 2, 5, 6])

In [38]:
photo[0:100, 0:100] = crop_resize

In [39]:
cv2.imshow('vimal', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [82]:
m = [1,2,3,4,5,6]

In [83]:
cv2.imwrite('my.png', photo)

True

In [50]:
n = m

In [51]:
n

[1, 2, 3, 4, 5, 6]

In [52]:
m

[1, 2, 3, 4, 5, 6]

In [53]:
n

[1, 2, 3, 4, 5, 6]

In [54]:
n[2] = 1000

In [55]:
n

[1, 2, 1000, 4, 5, 6]

In [56]:
m

[1, 2, 1000, 4, 5, 6]

In [57]:
x=5

In [58]:
y=5

In [59]:
id(x)

140731673931648

In [60]:
id(y)

140731673931648

In [61]:
id(m)

2271397030472

In [62]:
m

[1, 2, 1000, 4, 5, 6]

In [63]:
n[1]= 111111

In [64]:
n

[1, 111111, 1000, 4, 5, 6]

In [65]:
m

[1, 111111, 1000, 4, 5, 6]

In [69]:
newphoto =  photo.copy()

In [72]:
cv2.imshow('vimal', newphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [71]:
newphoto[0:100] = [0,255,0]

In [73]:
cv2.imshow('vimal', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [74]:
j = [1,2,3,4]

In [75]:
# tuple vs list

In [76]:
id(photo)

2271396983712

In [77]:
id(crop)

2271555764592

In [78]:
x=23536768887

In [79]:
y=x

In [80]:
id(x)

2271555790608

In [81]:
id(y)

2271555790608