In [35]:
import pandas as pd

In [36]:
dataset = pd.read_csv('SalaryData.csv')

In [37]:
dataset.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [38]:
# let take salary to be predicted from year of experience
y = dataset['Salary']

In [39]:
x = dataset['YearsExperience']

In [40]:
type(x)

pandas.core.series.Series

In [41]:
# reshape x into 2D array 
X = x.values.reshape(30,1)

In [42]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [43]:
# we need linear regression beacuse it is continuous data
from sklearn.linear_model import LinearRegression

In [44]:
# model be like ... y = b + cx b=bias c=weight/coefficient
model = LinearRegression()

In [45]:
# train model by fit function
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [58]:
z = model.predict([[1.1]])

In [59]:
z

array([36187.15875227])

In [56]:
z[0]

36187.15875226929

In [48]:
model.coef_ # it tells the value of coefficient in our case it is c

array([9449.96232146])

In [49]:
model.intercept_ # it tells the value of bias in our case it is b

25792.20019866871

In [50]:
# now lets save the model as we don't want to run the program again n again
from sklearn.externals import joblib

In [51]:
joblib.dump(model,'salary_model.pk1')

['salary_model.pk1']